name: build

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['26', '25', '24']

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ matrix.node }}

    - run: npm install
    - run: npm test

    - uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
